/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account-settings/': RouteRecordInfo<'/account-settings/', '/account-settings', Record<never, never>, Record<never, never>>,
    '/dashboards/classic/': RouteRecordInfo<'/dashboards/classic/', '/dashboards/classic', Record<never, never>, Record<never, never>>,
    '/dashboards/general/': RouteRecordInfo<'/dashboards/general/', '/dashboards/general', Record<never, never>, Record<never, never>>,
    '/dashboards/overview/': RouteRecordInfo<'/dashboards/overview/', '/dashboards/overview', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/system/customers/': RouteRecordInfo<'/system/customers/', '/system/customers', Record<never, never>, Record<never, never>>,
    '/system/employees/': RouteRecordInfo<'/system/employees/', '/system/employees', Record<never, never>, Record<never, never>>,
    '/system/ref/': RouteRecordInfo<'/system/ref/', '/system/ref', Record<never, never>, Record<never, never>>,
    '/system/repairs/': RouteRecordInfo<'/system/repairs/', '/system/repairs', Record<never, never>, Record<never, never>>,
    '/system/repairs/[repairID]': RouteRecordInfo<'/system/repairs/[repairID]', '/system/repairs/:repairID', { repairID: ParamValue<true> }, { repairID: ParamValue<false> }>,
    '/system/stock/': RouteRecordInfo<'/system/stock/', '/system/stock', Record<never, never>, Record<never, never>>,
    '/system/vendors/': RouteRecordInfo<'/system/vendors/', '/system/vendors', Record<never, never>, Record<never, never>>,
  }
}
